# Generated by Django 4.1.5 on 2023-08-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_contagemorcamento"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContagemOrcamento",
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="pag2",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1x Cartão de Crédito"),
                    (2, "2x Cartão de Crédito"),
                    (3, "3x Cartão de Crédito"),
                    (4, "4x Cartão de Crédito"),
                    (5, "5x Cartão de Crédito"),
                    (6, "6x Cartão de Crédito"),
                    (7, "Dinheiro"),
                ],
                null=True,
            ),
        ),
    ]
